name: Build

on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '.dockerignore'
      - 'LICENSE'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - '.dockerignore'
      - 'LICENSE'

jobs:
  build:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Clone the code
      uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version-file: go.mod

    - name: Build
      run: go build -v ./...
